version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    working_dir: /go/src/app
    volumes:
      - /home/samandar/Golang/docker:/go/src/app
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pg_data: